### ISSUE TITLE
not working with micro-2.0.8

### ISSUE THREAD

**Issue by levelibeka** [haqk/micro-bookmark#1]
I just installed the plugin by setting this in settings.json:

`    "pluginrepository": [
        "https://raw.githubusercontent.com/haqk/micro-bookmark/main/repo.json"
    ],
`

In micro, `plugin list` shows it's found by the editor.

However, the keyboard shortcuts don't work. I can see neither markers of the bookmarked lines, nor can jump around among bookmarks.

**Comment by haqk** [comment]
The plugin channel may not have been updated to include micro-bookmark yet, so just check that the plugin is actually in `~/.config/micro/plug`. If not, download the [latest release](https://github.com/haqk/micro-bookmark/releases), unzip/untar into `~/.config/micro/plug` and rename the folder to `bookmark`, then restart micro. If the default keybindings don't work, you can configure your own keys in `~/.config/micro/bindings`.

**Comment by levelibeka** [comment]
That's it. Thanks. Not the installation was the problem, but the default key bindings were presumably caught by MATE, so micro + plugin didn't receive the shortcuts.
