### ISSUE TITLE
bookmark positions go wrong with multiple tabs

### ISSUE THREAD

**Issue by levelibeka** [haqk/micro-bookmark#3]
How to reproduce:
- have more than one files open (I typically edit C sources);
- put a bookmark on the first tab;
- insert a line somewhere above the bookmark --> works well;
- now change to the second tab;
- put somewhere a bookmark;
- insert a line above the bookmark;

All the bookmarks on all tabs go crazy (invalid line positions).

**Comment by haqk** [comment]
Thanks for the heads up. The [latest release](https://github.com/haqk/micro-bookmark/releases/tag/v2.2.0) fixes this issue.
